services:
  url_shortener:
    container_name: url_shortener
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    environment:
      POSTGRES_HOSTNAME: postgresql
      POSTGRES_USER: url_shortener
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: url_shortener
    depends_on:
      - postgresql
  postgresql:
    container_name: postgresql
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: url_shortener
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: url_shortener
    volumes:
      - url_shortener_data:/var/lib/postgresql/data

volumes:
  url_shortener_data: {}
